apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "slack"
      group_by: ['alertname', 'cluster', 'service', 'job', 'pod']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 15m

      routes:
        - match:
          receiver: "slack"
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 15m
          continue: true

        - match:
          receiver: "email"
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 15m
          continue: true

    receivers:
      - name: "slack"
        slack_configs:
          - api_url: URL_HERE
            channel: "#infraestructure-alerts"
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            username: "Prometheus - Testing"
            text: "*Summary:* {{ .CommonAnnotations.summary }}\n*Description:* {{ .CommonAnnotations.description }}"
            send_resolved: false

      - name: "email"
        email_configs:
          - to: ""
            from: ""
            smarthost: ""
            auth_username: ""
            auth_identity: ""
            auth_password: ""
            require_tls: true
